version: '3.8'

x-app-service: &default-app
  build: .
  command: ''
  environment:
    - MONGO_URL=mongodb://mongo:27017/dev

  volumes:
    - .:/code:delegated
    - node_modules:/code/node_modules:delegated

services:
  app:
    <<: *default-app

  mooc-backend:
    <<: *default-app
    command: bash -c "npm run start:mooc:backend"
    environment:
      - PORT=3000
    ports:
      - 3000:3000

volumes:
  node_modules:
  esdata:
    driver: local